# Generated by Django 5.1.3 on 2025-04-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("api_url", models.URLField(blank=True, null=True)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
        ),
    ]
