# Generated by Django 5.1.3 on 2025-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetTinkoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("figi", models.CharField(max_length=50, unique=True)),
                ("class_code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
