# Generated by Django 5.1.3 on 2025-04-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0002_assettinkoff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchange",
            name="commission",
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тарифа"),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Комиссия (%)"
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="brokers.exchange",
                        verbose_name="Биржа",
                    ),
                ),
            ],
        ),
    ]
