# Generated by Django 5.1.3 on 2025-04-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArbitrageOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("exchange_from", models.CharField(max_length=20)),
                ("exchange_to", models.CharField(max_length=20)),
                ("price_from", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_to", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {
                    ("asset", "exchange_from", "exchange_to", "is_active")
                },
            },
        ),
    ]
