# Generated by Django 5.1.3 on 2025-05-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbitrage_situation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitrageopportunity",
            name="link_from",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arbitrageopportunity",
            name="link_to",
            field=models.URLField(blank=True, null=True),
        ),
    ]
